source 'https://rubygems.org'

gem 'oj', '3.8.1'
gem 'json', '2.3.0'
gem 'async-http', '0.50.7'
gem 'ext_monitor', '0.1.2'
gem 'fluentd', '1.11.4'
gem 'bigdecimal', '1.4.4'
gem 'activesupport', '6.0.3.3'
gem 'fluent-plugin-concat', '2.4.0'
gem 'fluent-plugin-detect-exceptions', '0.0.13'
gem 'fluent-plugin-kubernetes_metadata_filter', '2.5.2'
gem 'fluent-plugin-multi-format-parser', '1.0.0'
gem 'fluent-plugin-prometheus', '1.8.4'
gem 'fluent-plugin-rewrite-tag-filter', '2.3.0'
#gem 'fluent-plugin-splunk-enterprise', '0.10.2'
gem 'fluent-plugin-splunk-hec', '1.2.4'
gem 'fluent-plugin-elasticsearch', '4.2.2'
gem 'fluent-plugin-dedot_filter', '1.0.0'
gem 'fluent-plugin-route', '1.0.0'
gem 'fluent-plugin-conditional-tag-rewrite', '0.1.0'