source 'https://rubygems.org'

gem 'fluentd', '1.12.1'
gem 'fluent-plugin-prometheus', '1.8.5'
gem 'fluent-plugin-kubernetes_metadata_filter', '2.6.0'
gem 'fluent-plugin-rewrite-tag-filter', '2.4.0'
gem 'fluent-plugin-record-modifier', '2.1.0'
gem 'fluent-plugin-splunk-hec', '1.2.4'
gem 'fluent-plugin-dedot_filter', '1.0.0'
gem 'fluent-plugin-elasticsearch', '5.0.0'
gem 'fluent-plugin-jq', '0.5.1'